### ISSUE TITLE
Implement audio_data API (for uploading recording data)

### ISSUE THREAD

**Issue by briangershon** [BryceHaley/team7-blackfoot-chat-app#5]
- [x] Call audio_data from frontend
- [x] #14

@kyirong6  The browser will post this as form data (`multipart/form-data`) (section will be called `recording` and filename will be `recording.wav` and is `audio/wav` mimetype). There's a 2nd multipart section called `english_term` that has the word.

<img width="251" alt="Screen Shot 2021-09-24 at 3 57 32 PM" src="https://user-images.githubusercontent.com/139330/134747635-7b95a5e2-b494-4325-915d-d52acb713328.png">

**Comment by briangershon** [comment]
Hey @kyirong6 on the frontend, I added Axios and also added a placeholder call in StoryCard to call the API.

<img width="751" alt="Screen Shot 2021-09-24 at 12 17 15 PM" src="https://user-images.githubusercontent.com/139330/134728833-4c3ce476-07e2-4bff-9bb9-0ec744f06d53.png">

**Comment by briangershon** [comment]
We'll sort out tonight. I misinterpreted API, so if this is for audio recording upload, it's in good shape. Then we'll just need the translation endpoint.

**Comment by briangershon** [comment]
Ok, I left this one for audio uploading (as you had originally intended) and created a new card for the translate one: https://github.com/BryceHaley/team7-blackfoot-chat-app/issues/6

**Comment by briangershon** [comment]
I just pushed up the "upload audio recording" code on the front-end. It posts to `/audio_data`. The API will need to support the multipart/form-data mime type. More details in card description above.

**Comment by kyirong6** [comment]
I pushed the functionality to save the audio recordings locally into a folder: `/backend/audio_data/<english_term>`. 

The filename of the recording is the current timestamp in`.wav` format: `/backend/audio_data/<english_term>/09.25.2021_02-00-45.wav`

Will start to implement Cloudinary as host of audio recordings.

**Comment by kyirong6** [comment]
Implemented service to upload audio files to Cloudinary. This issue can be closed.
