### ISSUE TITLE
New Translate API

### ISSUE THREAD

**Issue by briangershon** [BryceHaley/team7-blackfoot-chat-app#6]
- [ ] ~~Return blackfoot_term in API~~
- [ ] ~~Call API for translations and name of WAV file.~~
- [ ] Upload all WAV files in frontend in /public/audio

**Comment by kyirong6** [comment]
Striking out the two subtasks above as we are not using the backend to serve Blackfoot terms and translations.

**Comment by briangershon** [comment]
Yes, let's just close this one.

I moved the note about cleaning out the one test WAV file from our repo (in /public/audio) into another card.
